### PR TITLE
fix a minor bug in dashboard view.

### PR DESCRIPTION
**Pull request by Lostars**

### CODE REVIEW

**Comment by mostafasoufi** [comment]
Hi @Lostars,

I've checked. But I don't see any changes. Can you give me an example URL for a visitor?

**Comment by Lostars** [comment]
In file includes/classes/class-wp-statistics.php line 1245
@mostafasoufi

**Comment by mostafasoufi** [comment]
I know is in this file :) I need an example URL for the check with your change. e.g.

```
https://www.google.com
http://www.google.com
```

**Comment by Dedi-Data** [comment]
Hi,
Thank you for your report and commit

**Comment by Lostars** [comment]
https://***/wp-admin/admin.php?page=wps_visitors_page&hitdays=1
In each hit recored it shows the wrong url like "http://https://***.com"

**Pull request merged**
