### PR TITLE
Security issue with activating and deactivating add-ons

### PR DESCRIPTION
**Pull request by abdoljabbar**
Hi,
With this line of code, plugins could be activated or deactivated using GET parameters. Hackers can use a link to activate or deactivate plugins by sending it to an admin user.
You should add additional conditions to that.
Best

### CODE REVIEW

**Comment by mostafasoufi** [comment]
Hi @abdoljabbar 

Thank you for mentioning the issue, since the changes are just comments, then I could not merge the PR, but I'll work on that asap.

Thanks!

**Comment by abdoljabbar** [comment]
yes I know, just to mention the lines, so I close the PR

**Comment by abdoljabbar** [comment]
The codes have not been updated by you, so I need to reopen the PR just to remind

**Comment by mostafasoufi** [comment]
I've just fixed it in this commit https://github.com/wp-statistics/wp-statistics/commit/d23c1a5fbd0cfb49a170fae00a38004935f59b49

**Pull request closed without merging**
